<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MicroservicesArchitecture" nsURI="http://it.univaq.thesis.msa.arch"
    nsPrefix="msa">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ComposedBy" lowerBound="1"
        upperBound="-1" eType="#//MicroService" containment="true" eOpposite="#//MicroService/Compose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DividedIn" upperBound="-1"
        eType="#//Cluster" containment="true" eOpposite="#//Cluster/divide"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Teams" lowerBound="1" upperBound="-1"
        eType="#//Team" containment="true" eOpposite="#//Team/workFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Links" upperBound="-1"
        eType="#//Link" containment="true" eOpposite="#//Link/Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Developers" upperBound="-1"
        eType="#//Developer" containment="true" eOpposite="#//Developer/worksFor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroService" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Compose" eType="#//Product"
        eOpposite="#//Product/ComposedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BelongTo" eType="#//Cluster"
        eOpposite="#//Cluster/Contains"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expose" upperBound="-1"
        eType="#//Interface" containment="true" eOpposite="#//Interface/exposedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owned" eType="#//Team"
        eOpposite="#//Team/WorkOn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Contains" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/BelongTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="divide" eType="#//Product"
        eOpposite="#//Product/DividedIn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Developer" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksFor" eType="#//Product"
        eOpposite="#//Product/Developers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedBy" eType="#//MicroService"
        eOpposite="#//MicroService/expose"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dependency" eType="#//Product"
        eOpposite="#//Product/Links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedBy" upperBound="-1"
        eType="#//Developer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="WorkOn" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/Owned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workFor" eType="#//Product"
        eOpposite="#//Product/Teams"/>
  </eClassifiers>
</ecore:EPackage>
